### ISSUE TITLE
Migration took 4 times as long

### ISSUE THREAD

**Issue by grdw** [WeTransfer/ghost_adapter#66]
**Describe the bug**

Hey, it's me again 👋 😅 . I recently did a migration written something like this (I altered the names):

```ruby
class AddColumnAndOtherColumnToTable < ActiveRecord::Migration[6.1]
  def change
    change_table :table, bulk: true do |t|
      t.integer :column, limit: 2, null: false, default: 0
      t.references :other_column
      t.index :column
    end
  end
end
```

I ran the migration and because of `bulk: true` I expected it to convert into a single `ALTER TABLE` statement and copy in a single go, however what happened was that it took 4 times as long. Which is probably because it ran individual `ALTER TABLE` statements. One for adding:

1. one column `column`
2. one column `other_column`
3. an index for `other_column`
4. an index for `column`

It took 4 copy cycles for gh-ost, which is not really what I wanted to happen.

**To Reproduce**
\-

**Expected behavior**
I would love it if `bulk: true` was respected. 🙏 

**Screenshots**
\-

**Additional context**
Ruby version:
3.0.2

Relevant gem versions I have:
- ghost_adapter 3.0
- active_record 6.1.4.1
- mysql2 0.5.3

**Comment by acroos** [comment]
I don't think this is one that should be addressed by ghost adapter.  We would have to override the `change_table` behavior from ActiveRecord.  I want to avoid overriding this behavior whenever possible.  The reason we've done so with the index methods is because `gh-ost` requires an `ALTER TABLE` statement and the index methods in ActiveRecord don't use an `ALTER TABLE`
